let mapleader=" "

call plug#begin()
Plug 'tomasiser/vim-code-dark'
Plug 'w0ng/vim-hybrid'
Plug 'regularhunter/builder-dark.vim'

Plug 'habamax/vim-dir'
Plug 'girishji/scope.vim'
Plug 'neovimhaskell/haskell-vim'
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-surround'
Plug 'michaeljsmith/vim-indent-object'
Plug 'vim-python/python-syntax', { 'for': 'python' } 
Plug 'lervag/vimtex'
Plug 'vimwiki/vimwiki'
call plug#end()

packadd editexisting
packadd comment
packadd justify

let g:dir_invert_split = 1
let g:dir_change_cwd = 1
let g:codedark_modern=1
let g:codedark_italics=1
color codedark

set title
set nocompatible
set hidden
set noswapfile
set backspace=indent,eol,start
set expandtab
set tabstop=2
set shiftwidth=2
set smarttab
set nrformats-=octal
set ttimeout
set ttimeoutlen=100
set hlsearch
set ignorecase
set smartcase
set incsearch
nnoremap <silent> <Esc> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
set gdefault
set laststatus=2
set laststatus=2
set statusline=%f\      " file name
set statusline+=%h      " help file flag
set statusline+=%m      " modified flag
set statusline+=%r      " read only flag
set statusline+=\ %=      " align left
set statusline+=L:%l/%L   " line X of Y [percent of file]
"set statusline+=[%p%%]   " Line percentage
set statusline+=\ C:%c    " current column
set statusline+=\ B:%n    " Buffer number
set ruler
set wildmenu
set wildoptions=pum,fuzzy
set wildmode=noselect:full,full
set autocomplete
set complete+=F,o
set scrolloff=2
set sidescroll=1
set sidescrolloff=2
set display+=lastline
set display+=truncate
set number
set relativenumber
set cursorline
set showcmd
set signcolumn=number
set mouse=nvi
set list
set showbreak=↪\ 
set smartindent
set listchars=tab:»\ ,trail:·,extends:→,precedes:←,nbsp:␣,leadmultispace:│\ \ \ 
set wrap linebreak
set breakindent
set conceallevel=2
set formatoptions+=j
set autoindent
set autoread
set history=200
set tabpagemax=20
set sessionoptions-=options
set viewoptions-=options
set t_Co=16
set shell=fish
set nolangremap
filetype plugin indent on
syntax enable
command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis | wincmd p | diffthis
let g:is_posix = 1

" KEYMAPS
nnoremap Q gq
nnoremap <CR> :
vnoremap <CR> :
nnoremap <leader>b :Scope Buffer<CR>
nnoremap <leader>f :Scope File<CR>
nnoremap <leader>e :Dir .<CR>
nnoremap <silent> <Esc> :noh<CR>
nnoremap <silent> <M-j> :bn<CR>
nnoremap <silent> <M-k> :bp<CR>
nnoremap <silent> gb :bn<CR>
nnoremap <silent> gB :bp<CR>
vnoremap <silent> = "ty/<c-r>t<CR>
