#!/usr/bin/sh

# Here goes a while loop with a sleep.
# The issue with calling directly the command is that sometimes it does not show anything as the parameters are not updated
#
# TODO :
# kill previous instance of this script
# get the string from playerctl
# if empty wait 0.2 seconds
# repeat until whatchdog or succesful read from playerctl
#
notify-send " $(playerctl metadata --format "Now playing: {{ title }} - {{ artist }}") "
